language: node_js
node_js:
- '4.1'
before_script:
- npm install -g gulp
script: gulp test
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: gjlaubenstein@gmail.com
  api_key:
    secure: H+xVaST2p4/I1GDGPVkM6Z6LERg+0OSWp8dGk0ZTvthqhPo56JjmTWcYb+Excd8MtbtBsmBYlnARWlkjh5474Zh+EMmu75szAM8lRoo6nsy7gwyQy9MAKsdxGF7nnj8V/laObXme6aEDl9PnpnH995UhSNdS6hqDZayggI0Bz14hrqJT0YPD73+NTyTxp9FHJlvuf755IwchpH6CZCn5l/sw5LN6m+OmdOFIHM5fNz2AKlksPdsf6L7dr3eTO2KsKiyrYZGHxj/frwQLwW7z2gCZToZzGaj7n2bmRRdYJ7XJfKfWwbNgEh+uKw7i+Kv6kpjsAd/iZ8xBdr0quQuvn1pdOANxA5qXpTVdg50TgL2RiMtvEiqgI5/jLum8dH6G7Gync/jITcjopxHUz1trOc29ZqVcrSFb413VJM8DUYHp8Xo9/eJIxFELVuS2fgFMR2GrpcrTjnBMjseU/ISw7cuHTWKbkU52Ej+BgWtsSOAGRuqik5nY53SYUpSpW4EkcjzCe1Izg8Ytv3EfIpaAJdtJU5iIwHHpuW0NRydRxy8Ua9oiPKgKL3FZalJvIDA6ZHFDPtppbDpxzhqZCzmHMrdcPbbWOcGAZgMnWadhWDJ7+QRa1lxjfwEem0P1STfPpS4IArNDTdFEXywy7oJfAKQJwEA1E7IbWmjzYBtlVfQ=
  on:
    tags: true
    repo: gjlaubenstein/basic-twitter-client
env:
  global:
    secure: aNaZ1zg384uzxAtM4/UVjtrvF4ks3DfFpbEVsS7b9tnExg0HuGztoSuLMVT0jjCVFTEVhh/C1YpzUfm9ZEMSGz6j1CYBngrhw5VtC5VRtIRifNX4dFl81yK85rHR/BDDCihu45PTLetwte2bLbmMIaCHuTOVlgnBx77j99MH783l75w1uDJsgc5sP1mruYpq6XuHQ+OdlNWgQiYs1UuErFbZxB1liz5V6OQvp0PTsdDr+2q5Qb7tm1iydDsuqkTEXlTZKJbGCPeTC8lSnopUok6vY6aCQU+DTFGuGnKbsocM/HrCJemr6IGef/Orbvn7q4JNf15om9Pu2uREG5xEpJufFPvWWaoE7/cTN4VphlPGJTEp5IG/omYtfjaHek7Ni2ZwYa7JHOYe77ODid+TvYf47OMJoi7TvgR4X7nD4g0Gn2h0ajsQkeiywDu9gwlmjL3ixJEp2S6LcPlyEctPUNaJk6hiH7FdzUkOO96bMkGjBIYI99OVlrRPIHyvbf7Ns8PZDJvp2//R6pGOEGLFqom2ff6ZEO91YQQlkfhsbJbauQikLamN/cy+hSpMqeG8binzxdPKDSq1yqlmUmulpTnHMgllqpoozkrTICkuOL4hV4bEqjtUA+TtCN8phzEa8qwf4ZsX0PUdCZkBRGT3xAEytv+G0XeUQzXFiu0BFxo=